In [1]:
import numpy as np

In [2]:
data = np.loadtxt("./generated_hls/results.txt",delimiter=None, dtype=np.float64)

In [3]:
data

array([ 0.484375  ,  0.25976562, -0.45019531, ..., -1.25683594,
       -0.76074219, -0.34472656])

In [4]:
predictions = data.reshape(-1,5)

In [5]:
predictions

array([[ 0.484375  ,  0.25976562, -0.45019531, -0.37304688, -0.14746094],
       [-0.32226562,  1.50292969, -0.78613281, -0.41796875, -0.1796875 ],
       [-0.09472656, -0.21679688,  1.04003906, -0.47949219, -0.45703125],
       ...,
       [ 0.77929688, -0.3203125 ,  0.14453125, -0.41503906, -0.28222656],
       [-0.06933594,  0.83691406, -0.56835938, -0.31152344, -0.06933594],
       [ 0.58300781,  1.31347656, -1.25683594, -0.76074219, -0.34472656]])

In [6]:
argmax_indices = np.argmax(predictions, axis=1)

# Create one-hot encoded vectors
one_hot_vectors = np.eye(5)[argmax_indices]

In [7]:
one_hot_vectors

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [8]:
true_labels = np.load("./datasets/mps_data/y_N4.npy")

In [9]:
true_labels

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.]])

In [10]:
# Convert one-hot encoded vectors to class labels
y_true_labels = np.argmax(true_labels, axis=1)
y_pred_labels = np.argmax(predictions, axis=1)

# Compare accuracy using NumPy
accuracy_np = np.mean(y_true_labels == y_pred_labels)
print(f"Accuracy (NumPy): {accuracy_np:.2f}")

Accuracy (NumPy): 0.74
